custom workspace example
UniversalRobots/Universal_Robots_ROS_Tutorials pull request #12
Opened 2023-10-05 12:08 UTC by fdurchdewald

2023-11-08 14:49 UTC, fmauch requested changes
This looks like a very good tutorial so far. Please see my comments and suggestions.

2023-11-08 14:49 UTC, fmauch commented on ur_documentation/docs/source/examples/my_robot_cell/start_ur_driver.rst
> +Now that everything is in place, we can proceed to start up a driver instance. To initialize the ``ur_robot_driver`` using our customized workspace description, we need to create a launch file.
```suggestion
Now that everything is in place, we can proceed to start up a driver instance. To initialize the ``ur_robot_driver`` using our customized workcell description, we need to create a launch file.
```

2023-11-08 14:49 UTC, fmauch commented on ur_documentation/docs/source/examples/my_robot_cell/start_ur_driver.rst
> +    ros2 launch my_robot_cell_control start_robot.launch.py ur_type:=ur20 robot_ip:=yyy.yyy.yyy.yyy
Let's add a section where we start ursim and specify the IP address of the default URSim interface.

```suggestion
    ros2 launch my_robot_cell_control start_robot.launch.py ur_type:=ur20 robot_ip:=192.168.56.101
```

2023-11-08 18:45 UTC, fdurchdewald commented on my_robot_cell/my_robot_cell_description/meshes/notexture.png
notexture.png is used by 171005_Motek_Monitor_L.dae.

2023-11-08 19:37 UTC, fdurchdewald commented on my_robot_cell/my_robot_cell_description/urdf/my_robot_cell.urdf.xacro
> +    <origin xyz="0 -0.05 0" rpy="0 0 ${pi}" />
It's actually not needed to view the robot description. However, the control package loads these files into the URDF, so we need to declare these arguments and pass them to the ur_robot macro.

2023-11-08 20:20 UTC, fdurchdewald commented on my_robot_cell/my_robot_cell_moveit_config/launch/rsp.launch.py
When I wrote the tutorial, I intended to generate only the essential launch files. However, when I attempted to launch the move_group without rsp.launch.py, it didn't start. So, I decided to leave the launch files. Strangly, I just tried it again without those launch files, and it seems to work. I will remove them now.

2023-11-09 10:08 UTC, fmauch commented on ur_documentation/docs/source/examples/my_robot_cell/assemble_urdf.rst
> +    source install/setup.bash
```suggestion
    # source and build your workspace
    # cd to your colcon workspace root
    colcon build
    source install/setup.bash
```

2024-04-22 14:52 UTC, fmauch approved these changes
We should think about actually restructuring this a bit, but apart from that I am rather happy with it now. Needs https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/977 before merging

2024-04-29 14:21 UTC, merged